name: lint
# Run only on main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: npm run lint
